#!/bin/sh
if [ -n "$1" ]
then
  hg up tip
  chmod 664 *.rst
  make html OUTDIR=$1
  cd $1
  chmod 664 *.*
  for directory in "_sources" "_static" "doctrees"
  do
    chmod 775 $directory
    chmod 664 $directory/*
  done
fi
